Feature/form fix laravelcollectiveのインストールとフォームの修正
Tori1Mana5/drawingPost pull request #11
Opened 2023-03-12 14:23 UTC by Tori1Mana5

#　修正内容

- laravelcollectiveを使用してフォーム作成した部分、各URLを修正。
- 確認画面でformタグを使っていたため使わないように修正

2023-03-27 00:26 UTC, abs3tori requested changes

2023-03-27 00:26 UTC, abs3tori commented on src/app/Http/Controllers/PostController.php
> +        $body = old('body');
書き方が全体的にformの値が1つにしか対応できてないから、通常は複数になるのを想定してかいてほしい。

2023-03-27 00:26 UTC, abs3tori commented on src/app/Models/Post.php
> +    protected $hidden = ['email', 'password'];
その2つのカラムはpostにないから必要性がわからない

2023-03-27 00:26 UTC, abs3tori commented on src/resources/views/posts/index.blade.php
> +			<p>アカウント名: {{ $post['user']->username }}</p>
{{ $post->user->username }}

2023-04-05 14:11 UTC, Tori1Mana5 commented on src/app/Models/Post.php
> +    protected $hidden = ['email', 'password'];
削除した

2023-04-05 14:12 UTC, Tori1Mana5 commented on src/resources/views/posts/index.blade.php
> +			<p>アカウント名: {{ $post['user']->username }}</p>
こちらも修正<br>
https://github.com/Tori1Mana5/drawingPost/pull/11/commits/19e809886309156c7afa7c5fb6aea44d3f603463

2023-04-05 15:15 UTC, Tori1Mana5 commented on src/app/Http/Controllers/PostController.php
> +        $body = old('body');
https://github.com/Tori1Mana5/drawingPost/pull/11/commits/707533d4f7f09d66e748b016c4fd5ccd39012868

こちら修正

2023-05-08 05:39 UTC, merged